FileNotFoundError: File b'd:/python_work/machine-learning/gooseeker_utf8.csv' does not exist

In [56]:
# %load D:/python_work/machine-learning/gooseeker.py

# GooSeeker.py

import pandas as pd
import re
import numpy as np
import matplotlib.pyplot as plt

plt.style.use('ggplot')
%matplotlib inline

pd.set_option("display.max_columns", 30)
pd.set_option("display.max_colwidth", 100)
pd.set_option("display.precision", 3)

# Use the file location of GooSeeker.csv
CSV_PATH = r"d:/python_work/machine-learning/gooseeker_utf8.txt"

df = pd.read_csv(CSV_PATH)
df.columns

# df.head().T

su = df

len(su)

su['房型']

# 获取房型-面积-楼层-年代-租金 信息
def parse_info(row):
    # 处理房型信息
    if '室' in row:
        br, lr= row.split('室')[:2]
        lr, nr = lr.split('厅')[:2]
        return pd.Series({'Beds': br, 'Living': lr})
    elif '平米' in row:
        sqr, nr = row.split('平米')[:2]
        return pd.Series({'Square': sqr})
    elif '楼层' in row:
        lyr, nr = row.split('楼层')[:2]
        return pd.Series({'Floor': lyr})
    elif '元' in row:
        rt, nr = row.split('元')[:2]
        return pd.Series({'Rents': rt})

# 获取地铁信息，缺失值NaN暂不处理
    
#attr = ((((su['房型'].apply(parse_info))\
#         .join(su['面积'].apply(parse_info)))\
#         .join(su['楼层'].apply(parse_info)))\
#         .join(su['地铁'].apply(lambda x : 1 if '距离' in x else 0))).join(su['租金'].apply(parse_info))

sudf = (((su['房型'].apply(parse_info))\
         .join(su['面积'].apply(parse_info)))\
         .join(su['楼层'].apply(parse_info)))\
         .join(su['租金'].apply(parse_info))
    
sudf.loc[:, 'Floor'] = sudf['Floor'].map(lambda x : 0 if '低' in x else (1 if '中' in x else 2))
# data type reverse
sudf.loc[:, 'Beds'] = sudf['Beds'].astype(int)
sudf.loc[:, 'Living'] = sudf['Living'].astype(int)
sudf.loc[:, 'Square'] = sudf['Square'].astype(int)
sudf.loc[:, 'Rents'] = sudf['Rents'].astype(int)
sudf.loc[:, 'Floor'] = sudf['Floor'].astype(int)

sudf.info()

#sudf['Floor'].apply(lambda x : 0 if '低' in x 1 elif '中' in x else 2)

     Beds  Living  Square  Floor  Rents
0       2       1      15      0   2700
1       2       1      65      2   2800
2       2       1       8      1   2660
3       2       1      75      1   2700
4       4       1      10      2   2530
5       3       1      12      1   2590
6       3       1      11      1   2930
7       3       1      11      2   2530
8       4       1      17      0   2560
9       3       1      12      0   2530
10      2       1       7      0   2730
11      4       1      12      2   2690
12      4       1      16      0   2590
13      2       1      11      2   2890
14      3       1       9      1   2560
15      2       1      11      1   2630
16      2       1       9      1   2560
17      3       1      14      0   2860
18      4       1      11      1   2960
19      4       1      13      2   2730
20      3       1      10      2   2790
21      3       1       7      0   2690
22      3       1      14      1   2660
23      3       1      14      2   2730
24      3       1      11      0   2890
25      3       1      10      1   2590
26      3       1      14      0   2790
27      3       1      11      2   2790
28      3       1      13      2   2890
29      3       1      12      1   2890
..    ...     ...     ...    ...    ...
187     4       1       9      1   2890
188     4       1      18      1   2830
189     3       1      20      0   2730
190     3       1      13      2   2660
191     3       1      14      0   2590
192     4       1      12      1   2590
193     3       1      12      2   2890
194     3       1      16      0   2590
195     3       1      18      0   2890
196     3       1      12      0   2790
197     3       1      12      2   2830
198     3       1      10      2   2790
199     3       1      10      2   2930
200     2       1      15      0   2560
201     6       1      25      1   2690
202     4       1      18      0   2590
203     3       1      12      0   2730
204     3       1      10      1   2860
205     3       1      15      0   2930
206     3       1      12      2   2790
207     3       1      12      1   2530
208     3       1      13      1   2530
209     4       1       8      0   2960
210     3       1      10      1   2860
211     3       1       7      2   2730
212     2       1      10      1   2590
213     3       1      15      1   2790
214     3       1      15      2   2690
215     3       1      10      0   2590
216     5       1       8      1   2560

[217 rows x 5 columns]